-- Seuil par population (doux, 3 paliers) : <8000->5, 8000-20000->10, >=20000->15
-- Source population : Wikidata. Ajustable par commune ensuite.

UPDATE communes SET seuil_preinscrits = 5 WHERE nom IN (
  'Amblève', 'Anhée', 'Anthisnes', 'Antoing', 'Assesse', 'Attert', 'Aubel', 'Baelen', 'Beaumont', 'Beauvechain', 'Berloz', 'Bertogne', 'Bièvre', 'Bouillon', 'Braives', 'Brugelette', 'Bullange', 'Burdinne', 'Burg-Reuland', 'Butgenbach', 'Celles', 'Cerfontaine', 'Chastre', 'Chièvres', 'Chiny', 'Clavier', 'Comblain-au-Pont', 'Crisnée', 'Dalhem', 'Daverdisse', 'Doische', 'Donceel', 'Ellezelles', 'Engis', 'Érezée', 'Estinnes', 'Étalle', 'Faimes', 'Fauvillers', 'Ferrières', 'Fexhe-le-Haut-Clocher', 'Flobecq', 'Florenville', 'Froidchapelle', 'Gedinne', 'Geer', 'Gesves', 'Gouvy', 'Hamoir', 'Hamois', 'Hastière', 'Havelange', 'Hélécine', 'Hensies', 'Herbeumont', 'Héron', 'Honnelles', 'Hotton', 'Houffalize', 'Houyet', 'Incourt', 'Ittre', 'La Hulpe', 'La Roche-en-Ardenne', 'Léglise', 'Lens', 'Libin', 'Lierneux', 'Limbourg', 'Lincent', 'Lobbes', 'Lontzen', 'Manhay', 'Marchin', 'Martelange', 'Meix-devant-Virton', 'Merbes-le-Château', 'Modave', 'Momignies', 'Mont-de-l''Enclus', 'Mont-Saint-Guibert', 'Musson', 'Nandrin', 'Nassogne', 'Ohey', 'Olne', 'Onhaye', 'Oreye', 'Ouffet', 'Paliseul', 'Pecq', 'Quiévrain', 'Ramillies', 'Remicourt', 'Rendeux', 'Rouvroy', 'Rumes', 'Saint-Georges-sur-Meuse', 'Saint-Hubert', 'Saint-Léger', 'Sainte-Ode', 'Sivry-Rance', 'Somme-Leuze', 'Stavelot', 'Stoumont', 'Tellin', 'Tenneville', 'Thimister-Clermont', 'Tinlot', 'Tintigny', 'Trois-Ponts', 'Vaux-sur-Sûre', 'Verlaine', 'Vielsalm', 'Villers-le-Bouillet', 'Viroinval', 'Vresse-sur-Semois', 'Waimes', 'Walhain', 'Wasseiges', 'Wellin'
);

UPDATE communes SET seuil_preinscrits = 10 WHERE nom IN (
  'Aiseau-Presles', 'Amay', 'Anderlues', 'Aubange', 'Awans', 'Aywaille', 'Bassenge', 'Beauraing', 'Belœil', 'Bernissart', 'Bertrix', 'Beyne-Heusay', 'Blegny', 'Boussu', 'Braine-le-Château', 'Brunehaut', 'Chapelle-lez-Herlaimont', 'Chaumont-Gistoux', 'Chimay', 'Ciney', 'Comines-Warneton', 'Court-Saint-Étienne', 'Couvin', 'Dinant', 'Dison', 'Dour', 'Durbuy', 'Écaussinnes', 'Éghezée', 'Erquelinnes', 'Esneux', 'Estaimpuis', 'Eupen', 'Farciennes', 'Fernelmont', 'Fléron', 'Floreffe', 'Florennes', 'Fontaine-l''Évêque', 'Fosses-la-Ville', 'Frasnes-lez-Anvaing', 'Genappe', 'Gerpinnes', 'Grez-Doiceau', 'Habay', 'Ham-sur-Heure-Nalinnes', 'Hannut', 'Herve', 'Jalhay', 'Jemeppe-sur-Sambre', 'Jodoigne', 'Juprelle', 'Jurbise', 'La Bruyère', 'La Calamine', 'Lasne', 'Le Rœulx', 'Les Bons Villers', 'Lessines', 'Leuze-en-Hainaut', 'Libramont-Chevigny', 'Malmedy', 'Marche-en-Famenne', 'Messancy', 'Mettet', 'Montigny-le-Tilleul', 'Morlanwelz', 'Neufchâteau', 'Neupré', 'Orp-Jauche', 'Pepinster', 'Péruwelz', 'Perwez', 'Philippeville', 'Plombières', 'Pont-à-Celles', 'Profondeville', 'Quaregnon', 'Quévy', 'Raeren', 'Rebecq', 'Rochefort', 'Saint-Vith', 'Seneffe', 'Silly', 'Sombreffe', 'Soumagne', 'Spa', 'Sprimont', 'Theux', 'Thuin', 'Villers-la-Ville', 'Virton', 'Visé', 'Walcourt', 'Wanze', 'Waremme', 'Welkenraedt', 'Yvoir'
);

UPDATE communes SET seuil_preinscrits = 15 WHERE nom IN (
  'Andenne', 'Ans', 'Arlon', 'Ath', 'Bastogne', 'Binche', 'Braine-l''Alleud', 'Braine-le-Comte', 'Charleroi', 'Châtelet', 'Chaudfontaine', 'Colfontaine', 'Courcelles', 'Flémalle', 'Fleurus', 'Frameries', 'Gembloux', 'Grâce-Hollogne', 'Herstal', 'Huy', 'La Louvière', 'Liège', 'Manage', 'Mons', 'Mouscron', 'Namur', 'Nivelles', 'Ottignies-Louvain-la-Neuve', 'Oupeye', 'Rixensart', 'Saint-Ghislain', 'Saint-Nicolas', 'Sambreville', 'Seraing', 'Soignies', 'Tournai', 'Tubize', 'Verviers', 'Waterloo', 'Wavre'
);

